### ISSUE TITLE
Pagination limits

### ISSUE THREAD

**Issue by kachnitel** [keboola/juicer#8]
The scroller should be able to stop pagination after a configured
- amount of time spent on the resource
- amount of requests (pages)
- amount of received data (guzzle 6 curl stats could be useful here)
- once a parameter reaches/exceeds value

The state of the scroller should be stored and returned by the application, together with an information saying the extraction is incomplete

**Comment by kachnitel** [comment]
Proposed state storage:

```
result: # pagenum
    $jobId:
        scrollerData:
            page: 5
            limit: 1000
            limitParam: count
        finished: true
        children:
            $childJobId:
                scrollerData: 
                    page: 15
                    limit: 1000
                    limitParam: count
                finished: false
```

Settings:

```
pagination:
    type: offset
    limit: 1000
    forceStopAfter:
        pages: 15
        #time: 180 # seconds
        #volume: 5M # get statistics from CURL - Guzzle 6
```

If stopped forcefully, it should be included in the result(`finished`: bool) => details for each resource _must_ be included in the return value, and the `scroller` object should be a part of each such detail.
